name: .NET Core - Phase 7 - Start Solution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.5
    - name: Install dependencies
      run: dotnet restore "./Phase 7/01. StartSolution/Pezza.sln"
    - name: Build
      run: dotnet build "./Phase 7/01. StartSolution/Pezza.sln" --configuration Release --no-restore
