name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore "./Phase 1/Code/FinalSolution/Pezza.sln"
    - name: Build
      run: dotnet build "./Phase 1/Code/FinalSolution/Pezza.sln" --configuration Release --no-restore
